

spring.datasource:
  url: jdbc:mysql://localhost:3306/employees?serverTimezone=UTC&autoReconnect=true
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: root

spring.jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:  
 port: 9076 
 
